name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Setup
        shell: bash
        env:
          COMMIT_GPG_KEY: ${{ secrets.COMMIT_GPG_KEY }}
          COMMIT_GPG_ID: ${{ secrets.COMMIT_GPG_ID }}
        run: |
          bash scripts/setup.sh
          bash scripts/gh-config.sh
          bash scripts/gh-gpg.sh

      - name: Deploy
        shell: bash
        env:
          OUTPUT: build
          BRANCH: gh-pages
        run: |
          bash scripts/build.sh $OUTPUT
          bash scripts/gh-deploy.sh $OUTPUT
