name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Setup
        shell: bash
        run: |
          bash scripts/setup.sh

      - name: Build
        shell: bash
        env:
          output: build
        run: |
          bash scripts/build.sh

          for i in `ls -A`; do \
          if [ "$i" == ".git" ]; then continue; fi;\
          if [ "$i" == "$output" ]; then continue; fi;\
          rm -rf $i; done
          for i in `ls -A $output`; do \
          mv -t . $output/$i; done
          rmdir $output

      - name: Deploy
        shell: bash
        env:
          GPG_KEY: ${{ secrets.COMMIT_GPG_KEY }}
          GPG_ID: ${{ secrets.COMMIT_GPG_ID }}
          branch: gh-pages
        run: |
          git config user.name       "github-actions[bot]"
          git config user.email      "59302530+tqfx@users.noreply.github.com"
          git config user.signingkey $GPG_ID
          git config commit.gpgsign  true
          git config core.autocrlf   input
          git config core.quotepath  false
          git config core.filemode   false
          git config core.ignorecase false
          git config --list
          git checkout --quiet --orphan $branch
          git add --all
          echo "$GPG_KEY" > $GPG_ID && gpg --import $GPG_ID && rm $GPG_ID
          git commit --quiet --signoff --message $(git rev-parse origin/master)
          git push --force origin $branch
