name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Setup
        shell: bash
        env:
          COMMIT_GPG_KEY: ${{ secrets.COMMIT_GPG_KEY }}
          COMMIT_GPG_ID: ${{ secrets.COMMIT_GPG_ID }}
        run: |
          git clone https://github.com/tqfx/scripts.git gh-scripts
          bash gh-scripts/gh-config.sh
          npm install -g tiddlywiki

      - name: Deploy
        shell: bash
        env:
          OUTPUT: build
          BRANCH: gh-pages
        run: |
          bash build.sh $OUTPUT
          bash gh-scripts/gh-deploy.sh $OUTPUT
